datasets:
  heat_load:
    column_mapping:
      categorical_features:
        - 'orientation' 
        - 'glazing_area_distribution'
      numerical_features:
        - 'relative_compactnes'
        - 'surface_area'
        - 'wall_area'
        - 'roof_area' 
        - 'overall_height'
        - 'glazing_area'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/ENB2012_data.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
