datasets:
  heat_load:
    column_mapping:
      categorical_features:
        - 'X6'
        - 'X8'
      numerical_features:
        - 'X1'
        - 'X2'
        - 'X3'
        - 'X4'
        - 'X5'
        - 'X7'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/ENB2012_data.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
